language: python
python:
  - "3.11"

install:
 - pip install -r requirements.txt
 - pip install black flake8 coverage
 - pip install coveralls

script:
 # 1. Check formatting (will fail if code isn't "Blackened")
 - black --check .
 # 2. Check for linting errors
 - flake8 .
 # 3. Run tests with coverage tracking
 - coverage run --source=polls,mysite manage.py test polls

after_success:
 - coveralls --service=travis-pro