language: python
python:
  - "3.11"

install:
 - pip install -r requirements.txt
 - pip install black flake8 coverage
 - pip install coveralls

script:
 # 1. Check formatting (will fail if code isn't "Blackened")
 - black --check .
 # 2. Check for linting errors
 - flake8 .
 # 3. Run tests with coverage tracking
 - coverage run --source=polls,mysite manage.py test polls

after_success:
 - coveralls --service=travis-pro

deploy:
  provider: elasticbeanstalk
  access_key_id: $access
  secret_access_key: $key
  region: "us-east-1"
  app: "swe1-app"
  env: "swe1-app-env"
  bucket_name: "elasticbeanstalk-us-east-1-227176596642"  # replace this
  on:
    branch: main

## Step 6: Add a `Procfile`

Create `Procfile` in your project root:

web: gunicorn mysite.wsgi --bind 0.0.0.0:8000