language: python
python:
  - "3.10"
  - "3.11"

install:
 - pip install -r requirements.txt
 - pip install black flake8 coverage coveralls

script:
 # 1. Check formatting (will fail if code isn't "Blackened")
 - black --check .
 # 2. Check for linting errors
 - flake8 . --max-line-length=88
 # 3. Run tests with coverage tracking
 - coverage run --source=djangotutorial manage.py test

after_success:
 # 4. Send the results to Coveralls to get your badge
 - coveralls